// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xxyqmtjkqmzpqtwvsfik.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh4eXFtdGprcW16cHF0d3ZzZmlrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU3MDc0ODIsImV4cCI6MjA2MTI4MzQ4Mn0.2QfTsU1H2LVfD0RSTjpS5jcHZFZ9XlXOrGMnpIkCNLo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);